### ISSUE TITLE
What is a move actually (question #19)

### ISSUE THREAD

**Issue by iddm** [dtolnay/rust-quiz#19]
I don't quite understand, how the revealing the details explains the behavior:

```rust
struct S;

impl Drop for S {
    fn drop(&mut self) {
        print!("1");
    }
}

fn main() {
    let s = S;
    let _ = s;
    print!("2");
}
```

> The relevant line is let _ = s. If this line does not move s then s will continue to live until the close curly brace and the program would print 21. But if this line does move s, without binding it, then the moved value of type S would be dropped immediately and the program would print 12.
>
> In fact s does not get moved and the output is 21.

If an object is moved, we do not need to call destructor (`Drop::drop`). So, if `let _ = s` performs a move, we don't care what it was with `s` object as the ownership has already been transferred to another object, and we are tracking another object's lifetime for calling `Drop::drop` on it instead of original one. Also if it is moved then it can't be dropped immediately, as again, the ownership has already been transferred, so dropping it immediately will leave another object (to which the original one was moved) in an invalid state.

Did I misinterpret this explanation or it is really incorrect or just written in a difficult-to-understand manner? Anyways, I'd like it to also explain move semantics in Rust (at least because it differs from C++ a bit).

P.S. Perhaps you meant `copying` or `cloning` in some places of the explanation, because if it was cloned and not moved, then it can be dropped safely. But again, as far as I saw the LLVM IR code and optimized rust, the drops are performed just before cleaning up the stack frame, so after all the code, the object was not dropped immediately.

**Comment by FraGag** [comment]
The question is essentially "Is `let _ = s;` equivalent to `drop(s);`?". It turns out that no; `drop(s);` moves `s`, so the destructor is invoked by the end of the statement (formally, it's invoked before `drop` returns), but `let _ = s;` doesn't move `s` and thus doesn't run the destructor.

> So, if `let _ = s` performs a move, we don't care what it was with s object as the ownership has already been transferred to another object

The thing is, if this performed a move, then it would move `s` into *nothing*, because `_` is not an identifier (it's a pattern that matches anything). Therefore, if the statement performed a move, one could expect `s` to be dropped immediately, since it's "moved to nothing", so to speak.
