### ISSUE TITLE
Question #19

### ISSUE THREAD

**Issue by Cerber-Ursi** [dtolnay/rust-quiz#5]
Not sure that it does qualify for a separate question, but this is somewhat fun to discover when playing with [this](https://dtolnay.github.io/rust-quiz/19):

```rust
struct S;

impl Drop for S {
    fn drop(&mut self) {
        print!("1");
    }
}

fn main() {
    let s = S;
    let _ = s;
    drop(s);
    let _ = s;
    let _ = print!("2");
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=d4953b586285f7e1ff01be117b14090e)

This code surprisingly does compile. It seemed that `let _ = ...` operations are essentially dropped entirely by the compiler, but `print!` is executed anyway.

**Comment by dtolnay** [comment]
Thanks! I believe this has to do with how re-initializing structs after move is okay.

```rust
struct S(i32);

fn main() {
    let mut s = S(0);
    drop(s);
    s.0 = 1; // okay
}
```

After moving, you can't read from the struct, but you can store to it to replace the data that got moved. `let _` is simply the boundary case that neither reads nor writes, so if writing is allowed then it seems harmless for `let _` to be allowed as well.

It is not clear how to turn this into a quiz question because I would prefer to stay away from "does this compile or not" style of questions. The user should be deciding between does it print X vs does it print Y, not between does it print X vs does it not compile.
